### ISSUE TITLE
Method 'play' cannot be called on 'AnimationAction?' because it is potentially null.

### ISSUE THREAD

**Issue by paultallard** [wasabia/three_dart#48]
Error when building application for Chrome.  three_dart_jsm/utils/SkeletonUtils.dart:179:28: Error: Method 'play' cannot be called on 'AnimationAction?' because it is potentially null.  in pubspec.yaml, reference is to   three_dart_jsm: ^0.0.5.  Normally I would ask someone and not submit an issue, but the submitter is anonymous.

**Comment by wasabia** [comment]
it is my fault, no fully tested. 
maybe still have other bugs. 
you can clone three_dart_jsm three_dart flutter_gl  from github. use pub dependencies from local
so you can fixed it quickly

**Comment by paultallard** [comment]
Thanks. I will try that next week.

Paul Allard
206-679-6315
________________________________

**Comment by paultallard** [comment]
I am having questions in the use of your flutter_gl package.  Can I ask a few questions or should I submit individual issues?

On no platform does the Triangle01 example work.  It only returns the same screen as the ExampleDemoTest, a varying colored square with no geometry.  I am running on Windows using Android Studio and testing platforms Chrome Web, Edge Web, Windows, and Android (Pixel 2 emulator and Samsung 7 physical device).

A previous version of your package listed Windows as a target.  The current version lists no targets.  What are the Targets for your package?

My target environment is Windows desktop.  According to your Readme file, Windows was supported but you have a separate package for flutter_gl_windows.  There are no examples or install instructions


  1.  Do I “pub add” both flutter_gl and flutter_gl_windows?
  2.  Do I import both flutter_gl and flutter_gl_windows?  I cannot seem to get an import address for flutter_gl_windows. So can I assume it is included in flutter_gl?

For Android Platform, I tried using ThreeEgl and could not find it.  I found a similar issue posted for George35mk at 2021-09-20 11:23 with no resolution.  A Google Search did not seem to find it.  Could you please update your ReadMe file to identify how to get (Pub Get?) ThreeEgl?

For Web, I am getting error LateInitializationError: Field 'gl' has not been initialized.  No combination of timing or sequence of statements seems to fix this.  See below for code.


  flutterGlPlugin = await FlutterGlPlugin();
  Map<String, dynamic> _options = {
    "antialias": true,
    "alpha": false,
    "width": width.toInt(),
    "height": height.toInt(),
    "dpr": dpr
  };
  await flutterGlPlugin.initialize(options: _options);
  // web does not need to use the fbo
  if (kIsWeb) {
    // web need wait dom ok!!!
    Future.delayed(const Duration(milliseconds: 100), () async {
      flutterGlPlugin.prepareContext();
      gl = flutterGlPlugin.gl;
    });
  } else {
    gl = flutterGlPlugin.gl;
    setupDefaultFBO(gl);
    sourceTexture = defaultFramebufferTexture;
  }

I would love to get this package to work.  I look forward to your reply.

Paul Allard
206-679-6315

**Comment by wasabia** [comment]
Hi @paultallard 

fixed Triangle demo [https://github.com/wasabia/flutter_gl](https://github.com/wasabia/flutter_gl)

pull code from github


ThreeEgl is from an aar 
check the example project copy the example/android/app/libs/aars/threeegl.aar to your app android project same path

windows app no need add flutter_gl_windows 
only add flutter_gl to pubspec.yaml

**Comment by paultallard** [comment]
Thanks for the update.  Yes, the example now works for me on Web browser targets (Chrome and Edge).
It is still not working on Windows target.  It shows the background texture but not the triangle.
Here is what I have done to debug that.
I removed flutter_gl_windows from pubspec.yaml. and I removed the web, Windows and MacOS libraries from project dependencies.
I left flutter_gl in pubspec.yaml.
Here are my only dependencies in pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gl: ^0.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
I upgraded to the newest Android Studio, Flutter and Dart plugins.  I ran pub upgrade and flutter doctor.  I fixed an issue with my JAVA_HOME environment variable and got a clean flutter doctor report.  I exited Android Studio and restarted it.  I recompiled the ExampleTriangle01.  Still not showing a Triangle in Windows target.

I had a problem while debugging the example.  Which version of OpenGL or WebGL are you using?  Are there some variations in your package that I need to be aware of?
I looked at your GL method signatures and noticed that

gl.createVertexArray() is consistent with the signature in WebGL2 as reported on the Mozilla MDN documentation pages.

(See WebGL2RenderingContext.createVertexArray() - Web APIs | MDN (mozilla.org)<https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/createVertexArray>)
When I checked OpenGL 3.0, 3.1, and 3.2, there is no function for gl.createVertexArray().  It does not exist until OpenGL 4.5 and there its signature is glCreateVertexArrays(GLsizei n, GLuint *arrays);  That is not consistent with the signature in your example.
(See (linked) OpenGL 4 Reference Pages (khronos.org)<https://www.khronos.org/registry/OpenGL-Refpages/gl4/>)

However, when I checked bufferData()

gl.bufferData(gl.ARRAY_BUFFER, vertices.length, vertices, gl.STATIC_DRAW) does not match any of the WebGL1 or Webgl2 signatures.

(see WebGLRenderingContext.bufferData() - Web APIs | MDN (mozilla.org)<https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData>)
But it does match the signature for OpenGL 3.0, through 4.5 on the Khronos reference pages.
(See (linked) OpenGL ES 3.0 Reference Pages (khronos.org)<https://www.khronos.org/registry/OpenGL-Refpages/es3.0/>)

So createVertexData() appears to be WebGL2 and bufferData() appears to be OpenGL 3.0!  Or did I get that wrong?  Which way should I go?
I have the same question for the shader code.  Originally it was a different version on MacOS and Windows but you have now commented that out.  Which version should I use for Windows?

Here is my system information.
Windows 10
Android Studio Chipmunk (2021,2,1, Build #AI-212.5712.43.2112.8512546)
HP laptop, Intel HD Graphics 630 with 5526 MB ROM
Intel Core i7-7700HQ
OpenGL version 4.5, build 22.20.16.4836
Also supports DirectX 9 and Vulkan 1.2.175
Java 64 bit, JDK 1.8.0_144, JRE 1.8.0_331
Flutter 3.0
Dart 2.17

I am very excited by your package and I look forward to getting it working.
I look forward to your response.  If you instead tell me to post this as a new issue I will do so.

Paul Allard
206-679-6315

**Comment by wasabia** [comment]
Hi @paultallard 
clone flutter_gl to local, use the local flutter_gl in pub 
[https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl_windows/windows/EglEnv.cpp#L10](https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl_windows/windows/EglEnv.cpp#L10)

now windows is use OpenGL 3.3 ? i am not sure, you can edit it, if you want different version,

webgl opengl opengles is different, so it is hard to have same api for flutter_gl
and shader is also different?

now flutter_gl only provide call native opengl on different platform.

if you want test is it work on windows, use [ExampleDemoTest.dart](https://github.com/wasabia/flutter_gl/blob/main/flutter_gl/example/lib/ExampleDemoTest.dart)

if you want use Triangle demo on windows,  maybe you need fix it yourself 😄

**Comment by paultallard** [comment]
Thanks for your quick response.  My Windows Laptop has OpenGL 3.0 to 4.5;  I assume I can address and use any of those versions.  I was telling you about issues with the specific GL calls in your example.  They appear to address different GL versions.  That may be contributing to why your example does not work on Windows.

I looked at your GL method signatures and noticed that gl.createVertexArray() is consistent with the signature in WebGL2 as reported on the Mozilla MDN documentation pages.

(See WebGL2RenderingContext.createVertexArray() - Web APIs | MDN (mozilla.org)<https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/createVertexArray>)
For OpenGL there is no function for gl.createVertexArray() before OpenGL 4.5.  in OpenGL 4.5 its signature is glCreateVertexArrays(GLsizei n, GLuint *arrays);  That is not consistent with the signature in your example.(See (linked) OpenGL 4 Reference Pages (khronos.org)<https://www.khronos.org/registry/OpenGL-Refpages/gl4/>)

When I checked bufferData(), the signature gl.bufferData(gl.ARRAY_BUFFER, vertices.length, vertices, gl.STATIC_DRAW) does not match any of the WebGL1 or WebGL2 signatures.

(see WebGLRenderingContext.bufferData() - Web APIs | MDN (mozilla.org)<https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData>)But it does match the signature for OpenGL 3.0, through 4.5 on the Khronos reference pages.
(See (linked) OpenGL ES 3.0 Reference Pages (khronos.org)<https://www.khronos.org/registry/OpenGL-Refpages/es3.0/>).  There is one difference, in OpenGL bufferData(), the size parameter requires the number of bytes (36) but your example only counts the number of entries (vertices.length = 9).

I will play with it and see whether I can get it working.  It would help if I had documentation on FlutterPlugin.  Does that documentation exist?

I am also unsure how the sourceTexture relates to the defaultFrameBufferTexture.  In setup, you set sourceTexture = defaultFrameBufferTexture but in rendering you only update the sourceTexture.  If the FBO is required then does gl.DrawArrays write to the sourceTexture or the defaultFrameBufferTexture?  Please let me know.

I will try to get it working for OpenGL 3.0 (shader version 1.3) so it will run on older Windows versions.  Do you agree with that choice?

If I get the triangle working then I will next try to get this example working.  Using textures in WebGL - Web APIs | MDN (mozilla.org)<https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL> One thing I lack is the matrix routines for Perspective and Projection.  This example uses a JavaScript library for that.  Are Matrix and Vector routines available that I can use in Flutter or through ffi?  I have written those routines in Java.  I can translate those routines from Java, but they can be very technical, tricky, and may run slowly in Flutter.  Anything you have would be helpful.

Paul Allard
206-679-6315

**Comment by wasabia** [comment]
now, i do not have an windows devices or windows environment, i try install virtual windows 11，but still have some problem, can not run, i give up, 😢 


if run on windows, this class is real call opengl api

[https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/lib/openGL/opengl/OpenGLContextDesktop.dart#L555](https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/lib/openGL/opengl/OpenGLContextDesktop.dart#L555)

[https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/lib/openGL/opengl/OpenGLContextES.dart#L11](https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/lib/openGL/opengl/OpenGLContextES.dart#L11)


if run on web, this is the bufferData api call 
[https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/lib/openGL/opengl/OpenGLContextWeb.dart#L225](https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/lib/openGL/opengl/OpenGLContextWeb.dart#L225)



about sourceTexture 
when you call [_gl.finish() ](https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/example/lib/ExampleDemoTest.dart#L197)

result will render to sourceTexture which bind to defaultFramebuffer, right?
then  var res = await flutterGlPlugin.updateTexture(sourceTexture);

[https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/example/lib/ExampleDemoTest.dart#L207](https://github.com/wasabia/flutter_gl/blob/774231f68d69be49cd0899be825b89ce56fd8ce8/flutter_gl/example/lib/ExampleDemoTest.dart#L207)

updateTexture is for flutter to update the result (is also sourceTexture, or any other opengl texture) we render to Texture widget

**Comment by paultallard** [comment]
Thanks for these references.  I am making some progress.  If you are interested, I will keep you informed of my progress.  Do you want me to keep you informed?

I found the enum values that I can use to interrogate the OpenGL state.  I added these 2 imports to ExampleTriangle01.dart


import 'package:flutter_gl/openGL/opengl/OpenGL20Constant.dart';
import 'package:flutter_gl/openGL/opengl/OpenGL30Constant.dart';

At the start of Prepare() I added these lines

if(!kIsWeb) {

  OpenGL20Constant eNum = OpenGL20Constant();
  print("OpenGL Version ${_gl.getString(eNum.VERSION)}");
  print("OpenGL Shading Language Version ${_gl.getString(eNum.SHADING_LANGUAGE_VERSION)}");
}

My laptop running Windows 10 and Intel 630 Chipset reports

  *   OpenGL 3.3.0 - Build 22.20.16.4836
  *   The Shader Language Version is also 3.30 - Build 22.20.16.4836

An Android Samsung 7 Emulator reports

  *   I/flutter ( 8244): OpenGL Version OpenGL ES 3.1 (4.5.0 NVIDIA 472.19) This uses an Nvidia graphics card on my laptop for the emulation.
  *   I/flutter ( 8244): OpenGL Shading Language Version OpenGL ES GLSL ES 3.10

A physical Samsung 7 device reports.  I think the physical device was updated by Somsung in 2018 so it is more advanced than my emulator.

  *   I/flutter ( 2189): OpenGL Version OpenGL ES 3.2 ***@***.*** ***@***.***, I8a9bdcf8d3) (Date:03/15/18)
  *   I/flutter ( 2189): OpenGL Shading Language Version OpenGL ES GLSL ES 3.20

I assume these are full OpenGL and not OpenGL ES.  The language spec for 3.3 says that it adds no new deprecated entries to 3.2 but that 3.2 has numerous deprecated entries from 3.1.  For that reason, I am planning to use 3.2 as my target implementation.  I think you were targeting OpenGL ES 3.0 but some of that has been deprecated.  Does 3.2 make sense to you?

The Khronos OpenGL reference pages reference no implementation for 3.3. I will use the OpenGL 3.2 reference pages as my reference implementation.

One issue I found, as I follow calls through the calling tree, some routines appear to reference GLES instead of OpenGL.  That begs the question, which version of OpenGL ES should I reference?  I will assume OpenGL ES 3.2.  If the syntax and arguments match then I will not worry.  If they do not match then I will raise that as an issue.  Do you agree with that approach?

Ultimately, I think we need 3 clean versions of ExampleTriangle01.dart.  For Browsers we want WebGL, for Windows we want OpenGL , for Android and iOS we want OpenGL ES.  If we can correctly set up FlutterGLPlugin to set the platform and have that drive the rest of the calls then we can still do this in one file.  Do you agree?

So, I ask again, Do you want me to keep you informed of my progress?

Paul Allard
206-679-6315

**Comment by wasabia** [comment]
you can keep it,

at the beginning, flutter_gl is for three_dart, so i only need support opengl api & shader version  align to webgl2

**Comment by paultallard** [comment]
Thanks for updating your ExampleTriangle01.dart!  I now have the ExampleTriangle01.dart working in Web Browsers, Windows and on my Samsung 7 Android Phone.  It is not yet working in my Android Studio Emulators.  I have not yet tried it on MacBook or iOS.

In the following I added vertex colors to the triangle and rotated it around the Y axis.  It works on all of the platforms I ID above.  It looks great and I thought you would like to see the updated code.  I made 19 changes.  Each is Identified by a comment starting with // ***

Here is the plain text.  Let me know whether you would want me to upload it a different way.


import 'dart:async';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

// *** Unused Import
// import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

// *** Removed--duplicates Material.dart
// import 'package:flutter/widgets.dart';
import 'package:flutter_gl/flutter_gl.dart';
// *** Used in Prepare() to check OpenGL version
import 'package:flutter_gl/openGL/opengl/OpenGL20Constant.dart';

class FlutterGLTriangleColor extends StatefulWidget {
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<FlutterGLTriangleColor> {
  late FlutterGlPlugin flutterGlPlugin;

  int? fboId;
  num dpr = 1.0;
  late double width;
  late double height;

  Size? screenSize;

  dynamic glProgram;
  dynamic _vao;

  dynamic sourceTexture;

  dynamic defaultFramebuffer;
  dynamic defaultFramebufferTexture;

  int n = 0;

  int t = DateTime.now().millisecondsSinceEpoch;

  @override
  void initState() {
    super.initState();

    print(" init state..... ");
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    width = screenSize!.width;
    height = width;

    flutterGlPlugin = FlutterGlPlugin();

    Map<String, dynamic> _options = {
      "antialias": true,
      "alpha": false,
      "width": width.toInt(),
      "height": height.toInt(),
      "dpr": dpr
    };

    await flutterGlPlugin.initialize(options: _options);

    print(" flutterGlPlugin: textureid: ${flutterGlPlugin.textureId} ");

    setState(() {});

    // web need wait dom ok!!!
    // *** Lint rule prefers const
    Future.delayed(const Duration(milliseconds: 100), () {
      setup();
    });
  }

  setup() async {
    // web no need use fbo
    if (!kIsWeb) {
      await flutterGlPlugin.prepareContext();

      setupDefaultFBO();
      sourceTexture = defaultFramebufferTexture;
    }

    setState(() {

    });

    prepare();

    // *** Modified to turn Animate back on
    animate();
  }

  initSize(BuildContext context) {
    if (screenSize != null) {
      return;
    }
    final mq = MediaQuery.of(context);

    screenSize = mq.size;
    dpr = mq.devicePixelRatio;

    print(" screenSize: ${screenSize} dpr: ${dpr} ");

    initPlatformState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Example app'),
        ),
        body: Builder(
          builder: (BuildContext context) {
            initSize(context);
            return SingleChildScrollView(child: _build(context));
          },
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            clickRender();
          },
          child: Text("Render"),
        ),
      ),
    );
  }

  Widget _build(BuildContext context) {
    return Column(
      children: [
        Container(
            width: width,
            height: width,
            color: Colors.black,
            child: Builder(builder: (BuildContext context) {
              if (kIsWeb) {
                return flutterGlPlugin.isInitialized
                    ? HtmlElementView(
                    viewType: flutterGlPlugin.textureId!.toString())
                    : Container();
              } else {
                return flutterGlPlugin.isInitialized
                    ? Texture(textureId: flutterGlPlugin.textureId!)
                    : Container();
              }
            })),
      ],
    );
  }

  // *** Modified to turn Animate back on, Lint rule prefers const
  animate() {
    render();

    Future.delayed(const Duration(milliseconds: 40), () {
      animate();
    });
  }

  setupDefaultFBO() {
    final _gl = flutterGlPlugin.gl;
    int glWidth = (width * dpr).toInt();
    int glHeight = (height * dpr).toInt();

    print("glWidth: ${glWidth} glHeight: ${glHeight} ");

    defaultFramebuffer = _gl.createFramebuffer();
    defaultFramebufferTexture = _gl.createTexture();
    _gl.activeTexture(_gl.TEXTURE0);

    _gl.bindTexture(_gl.TEXTURE_2D, defaultFramebufferTexture);
    _gl.texImage2D(_gl.TEXTURE_2D, 0, _gl.RGBA, glWidth, glHeight, 0, _gl.RGBA,
        _gl.UNSIGNED_BYTE, null);
    _gl.texParameteri(_gl.TEXTURE_2D, _gl.TEXTURE_MIN_FILTER, _gl.LINEAR);
    _gl.texParameteri(_gl.TEXTURE_2D, _gl.TEXTURE_MAG_FILTER, _gl.LINEAR);

    _gl.bindFramebuffer(_gl.FRAMEBUFFER, defaultFramebuffer);
    _gl.framebufferTexture2D(_gl.FRAMEBUFFER, _gl.COLOR_ATTACHMENT0,
        _gl.TEXTURE_2D, defaultFramebufferTexture, 0);
  }

  clickRender() {
    print(" click render ... ");
    render();
  }

  render() {
    final _gl = flutterGlPlugin.gl;

    int _current = DateTime.now().millisecondsSinceEpoch;

    // *** Modified to spin the triangle in a horizontal circle
    // and to add different colors to each vertex (See Shaders)
    int _delay = 1000;
    var deltaX = 0.5 * cos((_current - t) / _delay);
    var deltaY = 0.5 * sin((_current - t) / _delay);
    var deltaZ = 0.5 * (0.5 + 0.5 * sin((_current - t) / _delay));
    var vertices = new Float32List.fromList([
      -deltaX, -0.5, deltaZ, 1.0, 0.0, 0.0, // Vertice #2
      deltaX, -0.5, -deltaZ, 0.0, 1.0, 0.0, // Vertice #3
      0, 0.5, 0, 0.0, 0.0, 1.0, // Vertice #1
    ]);
    if(kIsWeb) {
      _gl.bufferData(_gl.ARRAY_BUFFER, vertices.length, vertices, _gl.STATIC_DRAW);
    } else {
      _gl.bufferData(_gl.ARRAY_BUFFER, vertices.lengthInBytes, vertices, _gl.STATIC_DRAW);
    }
    // *** End of Modification

    _gl.viewport(0, 0, (width * dpr).toInt(), (height * dpr).toInt());

    // *** Modified to give a more uniform color change between 0 and 1
    num _blue = 0.5 + 0.5 * sin((_current - t) / 500);
    // Clear canvas
    _gl.clearColor(1.0, 0.0, _blue, 1.0);
    _gl.clear(_gl.COLOR_BUFFER_BIT);

    _gl.drawArrays(_gl.TRIANGLES, 0, n); // using Fragment Color

    // *** Excessive print stmt
    // print(" render n: ${n} ");

    _gl.finish();

    // *** I added the setState() to ensure the widget is rebuilt with the above
    if (!kIsWeb) {
      setState(() {
        flutterGlPlugin.updateTexture(sourceTexture);
      });
    }
  }

  prepare() {
    final _gl = flutterGlPlugin.gl;

    // *** Added to report the OpenGL version in use
    if(!kIsWeb) {
      OpenGL20Constant eNum = OpenGL20Constant();
      print("OpenGL Version ${_gl.getString(eNum.VERSION)}");
      print("OpenGL Shading Language Version ${_gl.getString(
          eNum.SHADING_LANGUAGE_VERSION)}");
    }

    String _version = "300 es";

    // *** Updated this to 3.3 core.  It works in Windows and
    // on my Android Samsung 7.  Have not tested on MacBook or iOS
    if(!kIsWeb) {
      if (Platform.isMacOS || Platform.isWindows) {
        _version = "330 core";
      }
    }

    // *** Added Color to Vertex Data
    var vs = """#version ${_version}
      #define attribute in
      #define varying out
      layout (location = 0) attribute vec3 a_Position;
      layout (location = 1) attribute vec3 a_Color;
      out highp vec4 vertexColor;

      void main() {
        gl_Position = vec4(a_Position, 1.0);
        vertexColor = vec4(a_Color, 0.1);
      }
      """;

    // *** Passed color data from Vertex Shader
    var fs = """#version ${_version}
      in highp vec4 vertexColor;
      out highp vec4 pc_fragColor;
      #define FragColor pc_fragColor

      void main() {
        FragColor = vertexColor;
      }
      """;

    if (!initShaders(_gl, vs, fs)) {
      print('Failed to intialize shaders.');
      return;
    }

    // Write the positions of vertices to a vertex shader
    n = initVertexBuffers(_gl);
    if (n < 0) {
      print('Failed to set the positions of the vertices');
      return;
    }
  }

  initVertexBuffers(gl) {
    // Vertices
    var dim = 3;
    // *** Added Color data to Vertices
    var vertices = new Float32List.fromList([
      -0.5, -0.5, 0, 1.0, 0.0, 0.0, // Vertice #2
      0.5, -0.5, 0, 0.0, 1.0, 0.0, // Vertice #3
      0, 0.5, 0, 0.0, 0.0, 1.0, // Vertice #1
      ]);

    _vao = gl.createVertexArray();
    gl.bindVertexArray(_vao);

    // Create a buffer object
    var vertexBuffer = gl.createBuffer();
    if (vertexBuffer == null) {
      print('Failed to create the buffer object');
      return -1;
    }
    gl.bindBuffer(gl.ARRAY_BUFFER, vertexBuffer);

    if(kIsWeb) {
      gl.bufferData(gl.ARRAY_BUFFER, vertices.length, vertices, gl.STATIC_DRAW);
    } else {
      gl.bufferData(gl.ARRAY_BUFFER, vertices.lengthInBytes, vertices, gl.STATIC_DRAW);
    }

    // Assign the vertices in buffer object to a_Position variable
    var a_Position = gl.getAttribLocation(glProgram, 'a_Position');
    if (a_Position < 0) {
      print('Failed to get the storage location of a_Position');
      return -1;
    }

    // *** Position, Stride is now 4 * 6
    gl.vertexAttribPointer(
        a_Position, dim, gl.FLOAT, false, Float32List.bytesPerElement * 6, 0);
    gl.enableVertexAttribArray(a_Position);
    // *** Color, Stride is now 4 * 6, offset is now 4 * 3
    gl.vertexAttribPointer(
        1, dim, gl.FLOAT, false, Float32List.bytesPerElement * 6, Float32List.bytesPerElement * 3);
    gl.enableVertexAttribArray(1);

    // Return number of vertices
    return (vertices.length / dim).toInt();
  }

  initShaders(gl, vs_source, fs_source) {
    // Compile shaders
    // *** Added Print calls to help ID which Shader was not compiling
    print('** Vertex Shader ** \n$vs_source');
    var vertexShader = makeShader(gl, vs_source, gl.VERTEX_SHADER);
    print('** Fragment Shader ** \n$fs_source');
    var fragmentShader = makeShader(gl, fs_source, gl.FRAGMENT_SHADER);

    // Create program
    glProgram = gl.createProgram();

    // Attach and link shaders to the program
    gl.attachShader(glProgram, vertexShader);
    gl.attachShader(glProgram, fragmentShader);
    gl.linkProgram(glProgram);
    var _res = gl.getProgramParameter(glProgram, gl.LINK_STATUS);
    print(" initShaders LINK_STATUS _res: ${_res} ");
    if (_res == false || _res == 0) {
      print("Unable to initialize the shader program");
      return false;
    }

    // Use program
    gl.useProgram(glProgram);

    return true;
  }

  makeShader(gl, src, type) {
    var shader = gl.createShader(type);
    gl.shaderSource(shader, src);
    gl.compileShader(shader);
    var _res = gl.getShaderParameter(shader, gl.COMPILE_STATUS);
    if (_res == 0 || _res == false) {
      print("Error compiling shader: ${gl.getShaderInfoLog(shader)}");
      return;
    }
    return shader;
  }
}


Paul Allard
206-679-6315
