### ISSUE TITLE
Build fails on Matrix4 Name Conflict while running Flutter 3.3

### ISSUE THREAD

**Issue by paultallard** [wasabia/three_dart#72]
Building on Windows 10 in latest Android Studio for any target (Web, Windows, Android) with all dependencies updated I upgraded to Flutter 3.3 and build immediately fails with 

/D:/pault/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/three_dart-0.0.11/lib/three3d/loaders/MaterialLoader.dart(224,45): error G2A256DBA: 'Matrix4' is imported from both 'package:vector_math/vector_math_64.dart' and 'package:three_dart/three3d/math/index.dart'. [D:\AndroidStudioProjects\flutter_three_dart\build\windows\flutter\flutter_assemble.vcxproj]
D:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'D:\AndroidStudioProjects\flutter_three_dart\build\windows\CMakeFiles\e6089758533f32596e11ebdaf060e0f1\flutter_windows.dll.rule;D:\AndroidStudioProjects\flutter_three_dart\build\windows\CMakeFiles\a6c6cc4e386a0a14fcca9d2b3ff72fc2\flutter_assemble.rule' exited with code 1. [D:\AndroidStudioProjects\flutter_three_dart\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.

I tried this on several projects including the three_dart example and got the same error on all target platforms.  

Flutter Doctor returns
D:\pault\Tools\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
    • Flutter version 3.3.0 on channel stable at D:\pault\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (9 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/pault/AppData/Local/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/pault/AppData/Local/Android/sdk
    • Java binary at: c:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.1)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31613.86
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio
    • Android Studio at c:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = c:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1889]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

Pubspec.yaml contains
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  three_dart: ^0.0.10
  three_dart_jsm: ^0.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

Using aliases on imports do not seem to avoid this error
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_gl/flutter_gl.dart';
import 'package:three_dart/three_dart.dart' as THREE;
import 'package:three_dart_jsm/three_dart_jsm.dart' as THREE_JSM;
 Let me know whether you need additional files or information.

**Comment by paultallard** [comment]
Easy to duplicate on Flutter 3.3 in Windows 10 in Android Studio.  Create a new Flutter Project with any target environment.  On that new project, follow the install process for three_dart.  In Main.dart add the import statement for three_dart.  Build the app.  Error happens quickly and build ends.  I also submitted an issue for Flutter (111155), but they already closed it saying this was a package plugin issue.

**Comment by wasabia** [comment]
```
import 'package:flutter/foundation.dart' hide Matrix4;
import 'package:three_dart/three_dart.dart'
```

or 

```
import 'package:flutter/foundation.dart';
import 'package:three_dart/three_dart.dart' as THREE;
```

**Comment by SerJoG** [comment]
@wasabia sorry fot bothering you. I need this library for a project in my startup. I tried this library and three model viewer but both doesn't work. You suggest two import but its all useless 'cause the problem is in the library u made and not in the example code. You have to update the library. This library (resolved this problem) works for android and ios?

**Comment by paultallard** [comment]
Here is additional information.  I downgraded Flutter to get back my builds.  Before I did, all of my three_dart imports were aliased as in your 2nd example (as THREE) and I still got this error.

Paul Allard
206-679-6315
________________________________

**Comment by wasabia** [comment]
try hide Matrix4 in main.dart 


```
import 'package:flutter/material.dart' hide Matrix4;
import 'ExampleApp.dart';

void main() {
  runApp(const ExampleApp());
  // runApp(MaterialApp(home: multi_views(fileName: 'multi_views'),));
}

```

**Comment by wasabia** [comment]
@paultallard  @SerJoG

**Comment by SerJoG** [comment]
@wasabia I already tried to downgrading and hide but it doesn't work. The problem is not in my code, I hate repeat things.

**Comment by wasabia** [comment]
Hi @SerJoG 
I tried Flutter 3.0.5 can't reproduce.

Flutter 3.3.0 it's reproduce

**Comment by wasabia** [comment]
Hi @SerJoG 
I tried Flutter 3.0.5 can't reproduce.

Flutter 3.3.0 it's reproduce

**Comment by wasabia** [comment]
[https://github.com/wasabia/three_dart/blob/main/lib/three3d/loaders/index.dart#L25](https://github.com/wasabia/three_dart/blob/main/lib/three3d/loaders/index.dart#L25)

fixed

**Comment by SerJoG** [comment]
you updated the repo but did you update the flutter package on pub.dev? 'cause i still have this issue.

**Comment by SerJoG** [comment]
Your issue is not in math.dart but in Matrix4, u have to change the name and then all works without hide or something similar.

**Comment by wasabia** [comment]
> Your issue is in Matrix4, u have to change the name and then all works without hide or something similar.

Matrix4 is also used elsewhere, but only one problem here。Confuse 😄

**Comment by SerJoG** [comment]
if you tested it and it works, could you please update this: 
![image](https://user-images.githubusercontent.com/23215134/189934996-e073b513-97ce-4597-8d27-e020bb1a0ecb.png)

**Comment by wasabia** [comment]
[https://pub.dev/packages/three_dart](https://pub.dev/packages/three_dart)

Done.

**Comment by paultallard** [comment]
Question:  Do the import aliases have to be upper case as in import 'package:three_dart/three_dart.dart' as THREE;

I switched to lower case because the linter doesn’t like upper case aliases.  Probably a silly question, but lower case was not working and I am avoiding Flutter 3.3 without a better idea.

Paul Allard
206-679-6315

**Comment by paultallard** [comment]
The Hide command worked.  May I ask another question?

How should I populate BufferGeometry?  Currently I use setAttribute from Float32Arrays as in the following.
My issue is how to define the Float32Arrays?  These do not appear to be in three_dart.  I currently get them from package:flutter_gl.dart
I converted this code from Java where I used Float32Arrays directly with OpenGL.  I am building for a Windows target.


import 'package:three_dart/three_dart.dart' as three;
import 'package:flutter_gl/flutter_gl.dart' as GL;
…

three.BufferGeometry geometry = three.BufferGeometry();
…

GL.Float32Array positions = GL.Float32Array(vertexCount * posLength);
GL.Float32Array normals = GL.Float32Array(vertexCount * normLength);
GL.Float32Array colors = GL.Float32Array(vertexCount * colorLength);
GL.Float32Array texCoords = GL.Float32Array(vertexCount * texLength);
for (var vertex in vertexData) {
  positions.set(vertex['pos'] as List<double>, posIdx);
  normals.set(vertex['norm'] as List<double>, normIdx);
  colors.set(vertex['color'] as List<double>, colorIdx);
  texCoords.set(vertex['tex'] as List<double>, texIdx);
  posIdx += posLength;
  normIdx += normLength;
  colorIdx += colorLength;
  texIdx += texLength;
}

// Set Buffer Attributes from Typed Arrays
geometry.setAttribute('position',
    three.Float32BufferAttribute(positions, posLength));
geometry.setAttribute('normal',
    three.Float32BufferAttribute(normals, normLength));
geometry.setAttribute('color',
    three.Float32BufferAttribute(colors, colorLength));
geometry.setAttribute('uv',
    three.Float32BufferAttribute(texCoords, texLength));

Can you help me with that question?

Paul Allard
206-679-6315
